import chalk from 'chalk';
import { existsSync, readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, resolve } from 'path';
import { getConfig } from '../utils/config.js';

const SOUL_SPEC_FILES = ['SOUL.md', 'IDENTITY.md', 'AGENTS.md', 'HEARTBEAT.md', 'STYLE.md'];

interface ExportOptions {
  output?: string;
  dir?: string;
}

function readSoulFiles(dir: string): Map<string, string> {
  const files = new Map<string, string>();
  for (const filename of SOUL_SPEC_FILES) {
    const filepath = join(dir, filename);
    if (existsSync(filepath)) {
      files.set(filename, readFileSync(filepath, 'utf-8').trim());
    }
  }
  return files;
}

function readSoulJson(dir: string): Record<string, unknown> | null {
  const p = join(dir, 'soul.json');
  if (existsSync(p)) {
    try { return JSON.parse(readFileSync(p, 'utf-8')); } catch { return null; }
  }
  return null;
}

function toClaudeMd(files: Map<string, string>, meta: Record<string, unknown> | null): string {
  const sections: string[] = [];

  // Header
  const name = meta?.displayName || meta?.name || 'AI Agent';
  const version = meta?.version || '';
  const desc = meta?.description || '';
  sections.push(`# ${name}${version ? ` v${version}` : ''}`);
  if (desc) sections.push(`> ${desc}`);
  sections.push('');
  sections.push('<!-- Generated by ClawSouls CLI (clawsouls export --format claude-md) -->');
  sections.push('<!-- Source: https://clawsouls.ai -->');
  sections.push('');

  // SOUL.md → core persona
  const soul = files.get('SOUL.md');
  if (soul) {
    sections.push('## Persona');
    sections.push('');
    sections.push(soul);
    sections.push('');
  }

  // IDENTITY.md → identity details
  const identity = files.get('IDENTITY.md');
  if (identity) {
    sections.push('## Identity');
    sections.push('');
    sections.push(identity);
    sections.push('');
  }

  // STYLE.md → communication style
  const style = files.get('STYLE.md');
  if (style) {
    sections.push('## Communication Style');
    sections.push('');
    sections.push(style);
    sections.push('');
  }

  // AGENTS.md → workflow
  const agents = files.get('AGENTS.md');
  if (agents) {
    sections.push('## Workflow');
    sections.push('');
    sections.push(agents);
    sections.push('');
  }

  // HEARTBEAT.md → periodic checks
  const heartbeat = files.get('HEARTBEAT.md');
  if (heartbeat) {
    sections.push('## Periodic Checks');
    sections.push('');
    sections.push(heartbeat);
    sections.push('');
  }

  return sections.join('\n').trimEnd() + '\n';
}

function toSystemPrompt(files: Map<string, string>, meta: Record<string, unknown> | null): string {
  const parts: string[] = [];

  const name = meta?.displayName || meta?.name || 'AI Agent';
  parts.push(`You are ${name}.`);

  const soul = files.get('SOUL.md');
  if (soul) parts.push('', soul);

  const identity = files.get('IDENTITY.md');
  if (identity) parts.push('', '---', '', identity);

  const style = files.get('STYLE.md');
  if (style) parts.push('', '---', '', style);

  const agents = files.get('AGENTS.md');
  if (agents) parts.push('', '---', '', agents);

  return parts.join('\n').trimEnd() + '\n';
}

const FORMATS: Record<string, { ext: string; convert: (files: Map<string, string>, meta: Record<string, unknown> | null) => string; label: string }> = {
  'claude-md': {
    ext: 'CLAUDE.md',
    convert: toClaudeMd,
    label: 'Claude Code / Cowork (CLAUDE.md)',
  },
  'system-prompt': {
    ext: 'system-prompt.txt',
    convert: toSystemPrompt,
    label: 'System Prompt (plain text)',
  },
};

export async function exportCommand(format: string, options: ExportOptions): Promise<void> {
  const fmt = FORMATS[format];
  if (!fmt) {
    console.error(chalk.red(`Unknown format: "${format}"`));
    console.error(`Available formats: ${Object.keys(FORMATS).join(', ')}`);
    process.exit(1);
  }

  // Resolve source directory
  let sourceDir: string;
  if (options.dir) {
    sourceDir = resolve(options.dir);
  } else {
    // Default: current workspace
    const config = getConfig();
    sourceDir = config.workspace;
  }

  if (!existsSync(sourceDir)) {
    console.error(chalk.red(`Directory not found: ${sourceDir}`));
    process.exit(1);
  }

  // Check for soul files
  const files = readSoulFiles(sourceDir);
  if (files.size === 0) {
    console.error(chalk.red('No soul files found (SOUL.md, IDENTITY.md, etc.)'));
    console.error(`Searched in: ${sourceDir}`);
    process.exit(1);
  }

  const meta = readSoulJson(sourceDir);
  const output = fmt.convert(files, meta);
  const outPath = options.output || fmt.ext;

  writeFileSync(outPath, output, 'utf-8');

  console.log(chalk.green(`✓ Exported to ${chalk.bold(outPath)}`));
  console.log(chalk.dim(`  Format: ${fmt.label}`));
  console.log(chalk.dim(`  Source: ${sourceDir}`));
  console.log(chalk.dim(`  Files included: ${[...files.keys()].join(', ')}`));

  if (format === 'claude-md') {
    console.log('');
    console.log(chalk.cyan('Usage with Claude Cowork:'));
    console.log(chalk.dim('  1. Copy CLAUDE.md to your Cowork shared folder'));
    console.log(chalk.dim('  2. Claude will automatically read it as project instructions'));
    console.log('');
    console.log(chalk.cyan('Usage with Claude Code:'));
    console.log(chalk.dim('  1. Place CLAUDE.md in your project root'));
    console.log(chalk.dim('  2. Claude Code picks it up automatically'));
  }
}
